# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.cache/wt} [current_project]
set_property parent.project_path {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/170081L/Downloads/nanoprocessor-master/nanoprocessor-master/Nano Processor/Nano Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Decoder_2_to_4.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Decoder_3_to_8.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Reg.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Reg_Bank.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Slow_Clk.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/HA.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/FA.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Add_Sub.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Tri_State_Buffer_8.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/TSB_Set_8_to_8.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Add_4.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/TSB_Set_2_to_8.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Decoder_1_to_2.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Tri_State_Buffer_4.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/TSB_Set_2_to_4.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/ROM_16_17.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Program_Counter.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Instruction_Decoder.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/Nano_Processor.vhd}
  {E:/Projects/Vivaldo/nanoprocessor/Nano Processor/Nano Processor.srcs/sources_1/new/D_Flip_Flop.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nano_Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nano_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nano_Processor_utilization_synth.rpt -pb Nano_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
